@startuml
hide circle
skinparam classBackgroundColor #Business
skinparam linetype ortho
skinparam Shadowing True

title Horizon Project: Entity Relationship Diagram

entity "Auth.Role" as role {
  *ID : bigint(19) <<generated epochdate>>
  --
  *Title : nvarchar(200)
  *Code : varchar(20) <<unique>>
  Description : nvarchar(4000)
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.Group" as role {
  *ID : bigint(19) <<generated epochdate>>
  --
  *Title : nvarchar(200)
  *Code : varchar(20) <<unique>>
  Description : nvarchar(4000)
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.Permission" as action {
  *ID : bigint(19) <<generated epochdate>>
  --
  *Title : nvarchar(200)
  *Code : varchar(20) <<unique>>
  Description : nvarchar(4000)
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.Form" as action {
  *ID : bigint(19) <<generated epochdate>>
  --
  *Title : nvarchar(200)
  *Code : varchar(20) <<unique>>
  Description : nvarchar(4000)
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.FormPermission" as action {
  *ID : bigint(19) <<generated epochdate>>
  --
  *FormId : integer(10) <<FK>>
  *PermissionId : integer(10) <<FK>>
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.RolePermission" as roleAction {
  *ID : bigint(19) <<generated epochdate>>
  --
  *RoleId : integer(10) <<FK>>
  *FormPermissionId : integer(10) <<FK>>
  *ActiveFrom : datetime
  ActiveTo : datetime
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.GroupPermission" as roleAction {
  *ID : integer(10) <<generated>>
  --
  *GroupId : integer(10) <<FK>>
  *FormPermissionId : integer(10) <<FK>>
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.Profile" as profile {
  *ID : integer(10) <<generated>>
  --
  FirstName : nvarchar(200)
  LastName : nvarchar(200)
  *Gender : char(1)
  Avatar : text
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.Users" as user {
  *ID : integer(10) <<generated>>
  --
  ProfileId :
  *ActiveFrom :
  ActiveTo :
  LastLogInDate : datetime
  WrongLogInCount :
  *Username : varchar(20) <<unique>>
  *Pass : varchar(255)
  PassSalt
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.UserRole" as userRole {
  *ID : integer(10) <<generated>>
  --
  *USER : integer(10) <<FK>>
  *ROLE : integer(10) <<FK>>
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "SCH_ORGANIZATION.TBL_ORGANIZATION" as organization {
  *ID : integer(10) <<generated>>
  --
  *NAME : varchar(50)
  *CODE : varchar(20) <<unique>>
  *ISACTIVE : char(1)
  PARENTID : integer(20) <<FK>>
  *CREATEDAT : date <<default: now()>>
  *CREATEDBY : integer(10)
  MODIFIEDAT : date
  MODIFIEDBY : integer(10)
}


entity "SCH_ORGANIZATION.TBL_BUILDING" as building {
  *ID : integer(10) <<generated>>
  --
  *NAME : varchar(50)
  *CODE : varchar(20) <<unique>>
  *ISACTIVE : char(1)
  *ORGANIZATION : integer(20) <<FK>>
  *FLOORCOUNT : integer(10)
  POSTALCODE : varchar(10)
  ADDRESS : varchar(255)
  PHONENUMBER : varchar(20)
  FAXNUMBER : varchar(20)
  *CREATEDAT : date <<default: now()>>
  *CREATEDBY : integer(10)
  MODIFIEDAT : date
  MODIFIEDBY : integer(10)
}

entity "SCH_ORGANIZATION.TBL_WORKSTATION" as workStation {
  *ID : integer(10) <<generated>>
  --
  *NAME : varchar(50)
  *CODE : varchar(20) <<unique>>
  *ISACTIVE : char(1)
  *IP : varchar(20) <<unique>>
  *BUILDING : integer(10) <<FK>>
  *FLOORNO : integer(10)
  *STAFF : integer(10) <<FK>>
  *CREATEDAT : date <<default: now()>>
  *CREATEDBY : integer(10)
  MODIFIEDAT : date
  MODIFIEDBY : integer(10)
}


entity "SCH_ORGANIZATION.TBL_DEPARTMENT" as department {
  *ID : integer(10) <<generated>>
  --
  *NAME : varchar(50)
  *CODE : varchar(20) <<unique>>
  *ISACTIVE : char(1)
  *ORGANIZATION : integer(10) 
  PARENTID : integer(20) <<FK>>
  *CREATEDAT : date <<default: now()>>
  *CREATEDBY : integer(10)
  MODIFIEDAT : date
  MODIFIEDBY : integer(10)
}

entity "SCH_HR.TBL_POSITION" as position {
  *ID : integer(10) <<generated>>
  --
  *NAME : varchar(50)
  *CODE : varchar(20) <<unique>>
  *ISACTIVE : char(1)
  *DEPARTMENT : integer(10) 
  *CREATEDAT : date <<default: now()>>
  *CREATEDBY : integer(10)
  MODIFIEDAT : date
  MODIFIEDBY : integer(10)
}

entity "SCH_HR.TBL_STAFF" as staff {
  *ID : integer(10) <<generated>>
  --
  *FIRSTNAME : varchar(50)
  *LASTNAME : varchar(50)
  *CODE : varchar(20) <<unique>>
  *ISACTIVE : char(1)
  *POSITION : integer(10) <<FK>>
  *DEPARTMENT : integer(10) 
  *CREATEDAT : date <<default: now()>>
  *CREATEDBY : integer(10)
  MODIFIEDAT : date
  MODIFIEDBY : integer(10)
}

role ||..o{ roleAction
action ||..o{ roleAction
user ||..o{ userRole
role ||..o{ userRole
organization |o..o{ organization
organization ||..o{ building
organization ||..o{ department
building ||..o{ workStation
staff ||..o{ workStation
department |o..o{ department
department ||..o{ position
position ||..o{ staff
staff |o..o{ user

@enduml