@startuml
skinparam Shadowing True

left to right direction

!include <tupadr3/common>
!include <tupadr3/font-awesome/desktop>
!include <tupadr3/font-awesome/server>
!include <tupadr3/font-awesome/database>
!include <tupadr3/font-awesome/users>
!include <tupadr3/font-awesome/mobile>
!include <tupadr3/font-awesome/bank>
!include <tupadr3/font-awesome/cloud>
!include <tupadr3/font-awesome/chrome>
!include <tupadr3/font-awesome/cubes>
!include <tupadr3/font-awesome/cogs>
!include <tupadr3/devicons/postgresql>
!include <tupadr3/devicons/nginx>
!include <office/Concepts/firewall_orange>

title Architecture of Horizon System

package "Organization Network Zone" as HorizonSystem{
    package "Microservice Layer" as microserviceLayer{
        FA_COGS(authMicroservice, "Authentication Microservice") #BUSINESS
        FA_COGS(financialMicroservice, "Finantial Management Microservice") #BUSINESS
        FA_COGS(hrMicroservice, "HR Management Microservice") #BUSINESS
        FA_COGS(organizationMicroservice, "Organization Management Microservice") #BUSINESS
        FA_COGS(projectMicroservice, "Project Management Microservice") #BUSINESS
        FA_COGS(resourceMicroservice, "Resource Management Microservice") #BUSINESS
    }
    package "API Layer" as apiLayer{
        DEV_NGINX(webServer1, "Load Balancer") #BUSINESS
        FA_CUBES(apis, "APIs") #BUSINESS
    }
    package "App Layer" as appLayer{
        FA_SERVER(mobileAppServer, "Mobile App Server") #BUSINESS
        FA_SERVER(webAppServer, "Web App Server") #BUSINESS
    }
    package "Security Layer" as securityLayer{
        OFF_FIREWALL_ORANGE(firewall,"Firewall") #BUSINESS
    }
    package "Data Layer" as dataLayer{
        DEV_POSTGRESQL(databaseServer, "Database Server") #BUSINESS
        FA_DATABASE(database, "Horizon Database") #BUSINESS
    }
    
    FA_DESKTOP(userStation, "Intranet Clients") #BUSINESS
}

FA_CLOUD(internet, "Internet") #BUSINESS
FA_CHROME(client, "Client's Browser") #BUSINESS
FA_MOBILE(mobileApp, "Mobile App") #BUSINESS

client <--> internet
mobileApp <--> internet
internet <--> firewall
firewall <--> mobileAppServer
firewall <--> webAppServer
databaseServer <--> database
webServer1 <--> apis
apis <--> authMicroservice
apis <--> financialMicroservice
apis <--> hrMicroservice
apis <--> organizationMicroservice
apis <--> projectMicroservice
apis <--> resourceMicroservice
authMicroservice <--> databaseServer
financialMicroservice <--> databaseServer
hrMicroservice <--> databaseServer
organizationMicroservice <--> databaseServer
projectMicroservice <--> databaseServer
resourceMicroservice <--> databaseServer
mobileAppServer <--> webServer1
webAppServer <--> webServer1
userStation <-> firewall
@enduml