@startuml
left to right direction
skinparam Shadowing True

!include <tupadr3/common>
!include <tupadr3/font-awesome/desktop>
!include <tupadr3/font-awesome-5/github>

title Development and Deployment Environments for Horizon Project

FA_DESKTOP(contributer1, "Contributer 1") #BUSINESS
FA_DESKTOP(contributer2, "Contributer 2") #BUSINESS
FA_DESKTOP(contributer3, "Contributer 3") #BUSINESS
FA_DESKTOP(contributerN, "Contributer N") #BUSINESS

FA_DESKTOP(teamLead, "Final Test by Team Lead") #BUSINESS
FA5_GITHUB(github, "Publish on GitHub") #BUSINESS

contributer1 --> teamLead
contributer2 --> teamLead
contributer3 --> teamLead
contributerN --> teamLead
teamLead --> github

@enduml