@startuml
skinparam Shadowing True
skinparam TitleFontSize 24pt

left to right direction

!include <tupadr3/common>
!include <tupadr3/font-awesome/desktop>
!include <tupadr3/font-awesome/server>
!include <tupadr3/font-awesome/database>
!include <tupadr3/font-awesome/users>
!include <tupadr3/font-awesome/mobile>
!include <tupadr3/font-awesome/bank>
!include <tupadr3/font-awesome/cloud>
!include <tupadr3/font-awesome/chrome>
!include <tupadr3/font-awesome/cubes>
!include <tupadr3/font-awesome/cogs>
!include <tupadr3/devicons/postgresql>
!include <tupadr3/devicons/nginx>
!include <office/Concepts/firewall_orange>

title Horizon Research Project (HRP) \n Architecture \n Version 24.12.27

package "Organization Network Zone" as HorizonSystem{
    package "Microservice Layer" as microserviceLayer{
        FA_COGS(adminService, "Administration Services") #BUSINESS
        FA_COGS(paService, "Productivity Assessment Services") #BUSINESS
        FA_COGS(hrService, "Human Resource Management Microservice") #BUSINESS
        FA_COGS(qcService, "Quality Management Services") #BUSINESS
        FA_COGS(projectService, "Project Management Microservice") #BUSINESS
    }
    package "API Layer" as apiLayer{
        DEV_NGINX(webServer1, "Load Balancer") #BUSINESS
        FA_CUBES(apis, "APIs") #BUSINESS
    }
    package "App Layer" as appLayer{
        FA_SERVER(mobileAppServer, "Mobile App Server") #BUSINESS
        FA_SERVER(webAppServer, "Web App Server") #BUSINESS
    }
    package "Security Layer" as securityLayer{
        OFF_FIREWALL_ORANGE(firewall,"Firewall") #BUSINESS
    }
    package "Data Layer" as dataLayer{
        DEV_POSTGRESQL(databaseServer, "Database Server") #BUSINESS
        FA_DATABASE(database, "Horizon Database") #BUSINESS
    }
    
    FA_DESKTOP(userStation, "Intranet Clients") #BUSINESS
}

FA_CLOUD(internet, "Internet") #BUSINESS
FA_CHROME(client, "Client's Browser") #BUSINESS
FA_MOBILE(mobileApp, "Mobile App") #BUSINESS

client <--> internet
mobileApp <--> internet
internet <--> firewall
firewall <--> mobileAppServer
firewall <--> webAppServer
databaseServer <--> database
webServer1 <--> apis
apis <--> adminService
apis <--> paService
apis <--> hrService
apis <--> qcService
apis <--> projectService
adminService <--> databaseServer
paService <--> databaseServer
hrService <--> databaseServer
qcService <--> databaseServer
projectService <--> databaseServer
mobileAppServer <--> webServer1
webAppServer <--> webServer1
userStation <-> firewall
@enduml