@startuml
hide circle
skinparam classBackgroundColor #Business
skinparam linetype ortho
skinparam Shadowing True

title Horizon Project: Entity Relationship Diagram

entity "General.PhoneType" as phoneType {
  *ID : bigint(19) <<generated epochdate>>
  --
  *Title : nvarchar(200)
  *Code : varchar(20) <<unique>>
  Description : nvarchar(4000)
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "General.AddressType" as pddressType {
  *ID : bigint(19) <<generated epochdate>>
  --
  *Title : nvarchar(200)
  *Code : varchar(20) <<unique>>
  Description : nvarchar(4000)
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "General.EducationLevel" as educationLevel {
  *ID : bigint(19) <<generated epochdate>>
  --
  *Title : nvarchar(200)
  *Code : varchar(20) <<unique>>
  Description : nvarchar(4000)
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.Role" as role {
  *ID : bigint(19) <<generated epochdate>>
  --
  *Title : nvarchar(200)
  *Code : varchar(20) <<unique>>
  Description : nvarchar(4000)
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.Group" as role {
  *ID : bigint(19) <<generated epochdate>>
  --
  *Title : nvarchar(200)
  *Code : varchar(20) <<unique>>
  Description : nvarchar(4000)
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.Permission" as action {
  *ID : bigint(19) <<generated epochdate>>
  --
  *Title : nvarchar(200)
  *Code : varchar(20) <<unique>>
  Description : nvarchar(4000)
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.Form" as action {
  *ID : bigint(19) <<generated epochdate>>
  --
  *Title : nvarchar(200)
  *Code : varchar(20) <<unique>>
  Description : nvarchar(4000)
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.FormPermission" as action {
  *ID : bigint(19) <<generated epochdate>>
  --
  *FormId : bigint(19) <<FK>>
  *PermissionId : bigint(19) <<FK>>
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.RolePermission" as roleAction {
  *ID : bigint(19) <<generated epochdate>>
  --
  *RoleId : integer(10) <<FK>>
  *FormPermissionId : integer(10) <<FK>>
  *ActiveFrom : datetime
  ActiveTo : datetime
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.GroupPermission" as roleAction {
  *ID : bigint(19) <<generated epochdate>>
  --
  *GroupId : bigint(19) <<FK>>
  *FormPermissionId : bigint(19) <<FK>>
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.Profile" as profile {
  *ID : bigint(19) <<generated epochdate>>
  --
  FirstName : nvarchar(200)
  LastName : nvarchar(200)
  *Gender : char(1) <<true=1, false=0>>
  Avatar : text
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}



entity "Auth.Users" as user {
  *ID : bigint(19) <<generated epochdate>>
  --
  *ProfileId : bigint(19) <<FK>>
  *ActiveFrom : datetime
  ActiveTo : datetime
  LastLogInDate : datetime
  WrongLogInCount : integer(10)
  *Username : varchar(20) <<unique>>
  *Pass : varchar(255)
  PassSalt : varchar(50)
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "Auth.UserRole" as userRole {
  *ID : bigint(19) <<generated epochdate>>
  --
  *UserId : bigint(19) <<FK>>
  *RoleId : bigint(19) <<FK>>
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "HumanResource.Company" as company {
  *ID : bigint(19) <<generated epochdate>>
  --
  *Title : varchar(50)
  *Code : varchar(20) <<unique>>
  ParentId : bigint(19) <<FK>>
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}


entity "HumanResource.Building" as building {
  *ID : bigint(19) <<generated epochdate>>
  --
  *NAME : varchar(50)
  *CODE : varchar(20) <<unique>>
  *ISACTIVE : char(1)
  *ORGANIZATION : integer(20) <<FK>>
  *FLOORCOUNT : integer(10)
  POSTALCODE : varchar(10)
  ADDRESS : varchar(255)
  PHONENUMBER : varchar(20)
  FAXNUMBER : varchar(20)
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "HumanResource.Department" as department {
  *ID : integer(10) <<generated>>
  --
  *NAME : varchar(50)
  *CODE : varchar(20) <<unique>>
  *ISACTIVE : char(1)
  *ORGANIZATION : integer(10) 
  PARENTID : integer(20) <<FK>>
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "HumanResource.Position" as position {
  *ID : integer(10) <<generated>>
  --
  *NAME : varchar(50)
  *CODE : varchar(20) <<unique>>
  *ISACTIVE : char(1)
  *DEPARTMENT : integer(10) 
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "HumanResource.Staff" as staff {
  *ID : integer(10) <<generated>>
  --
  *FIRSTNAME : varchar(50)
  *LASTNAME : varchar(50)
  *CODE : varchar(20) <<unique>>
  *ISACTIVE : char(1)
  *POSITION : integer(10) <<FK>>
  *DEPARTMENT : integer(10) 
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "HumanResource.ProfileAddressBook" as profileAddressBook {
  *ID : bigint(19) <<generated epochdate>>
  --
  *ProfileId : bigint(19) <<FK>>
  *AddressTypeId : bigint(19) <<FK>>
  *Address : nvarchar(4000)
  PostalCode : varchar(20)
  *IsActive : char(1) <<true=1, false=0>>
  *IsDeleted : char(1) <<true=1, false=0>>
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "HumanResource.ProfilePhoneBook" as profilePhoneBook {
  *ID : bigint(19) <<generated epochdate>>
  --
  *ProfileId : bigint(19) <<FK>>
  *AddressTypeId : bigint(19) <<FK>>
  *Address : nvarchar(4000)
  PostalCode : varchar(20)
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "HumanResource.ProfileEducation" as profileEducation {
  *ID : bigint(19) <<generated epochdate>>
  --
  *ProfileId : bigint(19) <<FK>>
  *AddressTypeId : bigint(19) <<FK>>
  *Address : nvarchar(4000)
  PostalCode : varchar(20)
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "HumanResource.ProfileJobExperience" as profileJobExperience {
  *ID : bigint(19) <<generated epochdate>>
  --
  *ProfileId : bigint(19) <<FK>>
  *AddressTypeId : bigint(19) <<FK>>
  *Address : nvarchar(4000)
  PostalCode : varchar(20)
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}

entity "HumanResource.ProfileCertificate" as profileCertificate {
  *ID : bigint(19) <<generated epochdate>>
  --
  *ProfileId : bigint(19) <<FK>>
  *AddressTypeId : bigint(19) <<FK>>
  *Address : nvarchar(4000)
  PostalCode : varchar(20)
  *IsActive : char(1)
  *IsDeleted : char(1)
  *CreatedAt : datetime <<default: now()>>
  *CreatedBy : bigint(19)
  ModifiedAt : timestamp
  ModifiedBy : bigint(19)
}



role ||..o{ roleAction
action ||..o{ roleAction
user ||..o{ userRole
role ||..o{ userRole
organization |o..o{ organization
organization ||..o{ building
organization ||..o{ department
building ||..o{ workStation
staff ||..o{ workStation
department |o..o{ department
department ||..o{ position
position ||..o{ staff
staff |o..o{ user

@enduml