@startuml
hide circle
skinparam classBackgroundColor #Business
skinparam linetype ortho
skinparam Shadowing True
skinparam TitleFontSize 72pt

title Horizon Research Project (HRP) \n Entity Relationship Diagram \n Version 25.4.2

entity "Basic.EducationLevel" as educationLevel {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Basic.Priority" as priority {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  *Ordering : integer
  *Color : varchar(7)
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Basic.IssueType" as issueType {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  *IconAddress : varchar(1000)
  *Color : varchar(7)
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Basic.Status" as status {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *Color : varchar(7)
  *IsToDo : boolean
  *IsInProgress : boolean
  *IsDone : boolean
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Basic.Resolvation" as resolvation {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *Color : varchar(7)
  *IsResolved : boolean
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Basic.MeetingType" as meetingType {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Basic.DocumentType" as documentType {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Basic.FileExtention" as fileExtention {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Basic.ContractType" as contractType {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Basic.TimeUnit" as timeUnit {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  BasedOnMiliscond : bigint(19)
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}


entity "UserManagement.Role" as role {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Groups" as groups {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Permission" as permission {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Form" as form {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  *Code : varchar(20) <<unique>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.FormPermission" as formPermission {
  *Id : bigint(19) <<serial>>
  --
  *FormId : bigint(19) <<FK>>
  *PermissionId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.RolePermission" as rolePermission {
  *Id : bigint(19) <<serial>>
  --
  *RoleId : integer(10) <<FK>>
  *FormPermissionId : integer(10) <<FK>>
  *ActiveFrom : datetime
  ActiveTo : datetime
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.GroupPermission" as groupPermission {
  *Id : bigint(19) <<serial>>
  --
  *GroupId : bigint(19) <<FK>>
  *FormPermissionId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.UserPermission" as userPermission {
  *Id : bigint(19) <<serial>>
  --
  *UserId : bigint(19) <<FK>>
  *PermissionId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Profile" as profile {
  *Id : bigint(19) <<serial>>
  --
  *FirstName : varchar(200)
  *LastName : varchar(200)
  *Gender : enum <<male, female>>
  Avatar : text
  Birthday : date
  PhoneNumber : varchar(20)
  MobileNumber : varchar(20)
  EmailAddress : varchar(200)
  Address : varchar(1000)
  PostalCode : varchar(20)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.Users" as user {
  *Id : bigint(19) <<serial>>
  --
  *ProfileId : bigint(19) <<FK>>
  *ActiveFrom : timestamp
  ActiveTo : timestamp
  LastLogInDate : timestamp
  LogInCount : integer(10) <<default: 0>>
  WrongLogInCount : integer(10) <<default: 0>>
  *Username : varchar(200) <<unique>>
  *Pass : varchar(255)
  PassSalt : varchar(50)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.UserRole" as userRole {
  *Id : bigint(19) <<serial>>
  --
  *UserId : bigint(19) <<FK>>
  *RoleId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "UserManagement.UserGroup" as userGroup {
  *Id : bigint(19) <<serial>>
  --
  *UserId : bigint(19) <<FK>>
  *GroupId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Company" as company {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(50)
  *Code : varchar(20) <<unique>>
  ParentId : bigint(19) <<FK>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Department" as department {
  *Id : integer(10) <<serial>>
  --
  *Title : varchar(50)
  *Code : varchar(20) <<unique>>
  *CompanyId : integer(10)  
  ParentId : integer(20) <<FK>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Position" as position {
  *Id : integer(10) <<serial>>
  --
  *Title : varchar(50)
  *Code : varchar(20) <<unique>>
  *DepartmentId : bigint(19) <<FK>>
  ParentId : bigint(19) <<FK>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Staff" as staff {
  *Id : integer(10) <<serial>>
  --
  *ProfileId : bigint(19) <<FK>>
  *ComapnyId : bigint(19) <<FK>>
  *StaffNumber : varchar(20) <<unique>>
  StartDate : date
  EndDate : date
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.StaffPsition" as staffPosition {
  *Id : integer(10) <<serial>>
  --
  *StaffId : bigint(19) <<FK>>
  *PositionId : bigint(19) <<FK>>
  StartDate : datetime
  EndDate : datetime
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.ProfileEducation" as profileEducation {
  *Id : bigint(19) <<serial>>
  --
  *ProfileId : bigint(19) <<FK>>
  *EducatioLevelId : bigint(19) <<FK>>
  DocumentId : bigint(19) <<FK>>
  *Title : varchar(255)
  CollegeName : varchar(255)
  StartDate : date
  EndDate : date
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.ProfileJobExperience" as profileJobExperience {
  *Id : bigint(19) <<serial>>
  --
  *ProfileId : bigint(19) <<FK>>
  *JobTitle : varchar(200)
  *CompanyName : varchar(200)
  StartDate : date
  EndDate : date
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.ProfileCertificate" as profileCertificate {
  *Id : bigint(19) <<serial>>
  --
  *ProfileId : bigint(19) <<FK>>
  *Title : varchar(200)
  *InstituteName : varchar(200)
  StartDate : date
  EndDate : date
  HasCertificate : boolean
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.WorkingTimeTable" as workingTimeTable { 
  *Id : bigint(19) <<serial>>
  --
  *CompanyId : bigint(19) <<FK>> <<composite unique>>
  *WorkingDay : enum <<Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday>> <<composite unique>>
  *StartTime : time
  *EndTime : time
  FloatingStartTime : time
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Holidaies" as holidaies {
  *Id : bigint(19) <<serial>>
  --
  *CompanyId : bigint(19) <<FK>> <<composite unique>>
  HolidayDate : date <<composite unique>> 
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Attendance" as attendance {
  *Id : bigint(19) <<serial>>
  --
  *StaffId : bigint(19) <<FK>>
  *WorkingDate : date
  *EnteranceType : enum <<enter, exit>>
  *EnternaceTime : time
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Leave" as leave {
  *Id : bigint(19) <<serial>>
  --
  *StaffId : bigint(19) <<FK>>
  LeaveType : enum <<fulltime, parttime>>
  *LeavingStartDate : date
  LeavingEndDate : date
  *LeavingStartTime : time
  *LeavingEndTime : time
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.WorkMission" as workMission {
  *Id : bigint(19) <<serial>>
  --
  *StaffId : bigint(19) <<FK>>
  *MissionStartDate : date
  MissionEndDate : date
  *MissionStartTime : time
  *MissionEndTime : time
  MissionLocation : varchar(255)
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Questionnaire" as questionnaire {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(200)
  Description : varchar(4000)
  *TotalScore : integer
  *AcceptableScore : integer
  *WarningScore : integer
  *DisasterScore : integer
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.QuestionnaireTargetDepartment" as questionnaireTargetDepartment {
  *Id : bigint(19) <<serial>>
  --
  *QuestionnaireId : bigint(19) <<FK>>
  *DepoartmentId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.Question" as question {
  *Id : bigint(19) <<serial>>
  --
  *QuestionnaireId : bigint(19) <<FK>>
  *Question : varchar(4000)
  *Score : integer
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.QuestionOption" as questionOption {
  *Id : bigint(19) <<serial>>
  --
  *QuestionId : bigint(19) <<FK>>
  *Title : varchar(4000)
  *Score : integer
  IsDescriptionRequired : boolean
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.QuestionnaireResult" as questionnaireResult {
  *Id : bigint(19) <<serial>>
  --
  *QuestionnaireId : bigint(19) <<FK>>
  *StaffId : bigint(19) <<FK>>
  *TotalScore : integer
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "HumanResource.QuestionnaireResultDetail" as questionnaireResultDetail {
  *Id : bigint(19) <<serial>>
  --
  *QuestionnaireResultId : bigint(19) <<FK>>
  *QuestionId : bigint(19) <<FK>>
  *QuestionOptionId : bigint(19) <<FK>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "DocumentManagement.Document" as document {
  *Id : bigint(19) <<serial>>
  --
  *TableName : varchar(255)
  *TableId : bigint(19)
  *DocumentTypeId : bigint(19) <<FK>>
  *FileExtentionId : bigint(19) <<FK>>
  *FileAddress: varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "DocumentManagement.ProjectWorkflowDocumentType" as projectWorkflowDocumentType {
  *Id : bigint(19) <<serial>>
  --
  *DocumentTypeId : bigint(19) <<FK>>
  *ProjectWorkflowId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}



entity "ProjectManagement.Project" as project {
  *Id : bigint(19) <<serial>>
  --
  *ConstructorCompnayId : bigint(19) <<FK>>
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  StartDate : date
  EndDate : date
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectStaffMember" as projectStaffMember {
  *Id : bigint(19) <<serial>>
  --
  *ProjectId : bigint(19) <<FK>>
  *StaffId : bigint(19) <<FK>>
  *IsProjectManager : boolean
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectDepartmentMember" as projectDepartmentMember {
  *Id : bigint(19) <<serial>>
  --
  *ProjectId : bigint(19) <<FK>>
  *DepartmentId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectWorkflow" as projectWorkflow {
  *Id : bigint(19) <<serial>>
  --
  *ProjectId : bigint(19) <<FK>>
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}


entity "ProjectManagement.ProjectWorkflowStatus" as projectWorkflowStatus {
  *Id : bigint(19) <<serial>>
  --
  *ProjectWorkflowId : bigint(19) <<FK>>
  *StatusId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectWorkflowProgress" as projectWorkflowProgress {
  *Id : bigint(19) <<serial>>
  --
  *Title : varchar(250)
  StartProjectWorkflowStatusId : bigint(19) <<FK>>
  IsFromStartPoint : boolean
  CanBeStartedFromAnyStatus : boolean
  EndProjectWorkflowStatusId : bigint(19) <<FK>>
  IsToEndPoint : boolean
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.Issue" as issue {
  *Id : bigint(19) <<serial>>
  --
  *ProjectId : bigint(19) <<FK>>
  AssineeeId : bigint(19) <<FK>>
  *Code : varchar(20) <<unique>>
  *Title : varchar(200)
  Description : varchar(4000)
  DueDate : date
  PriorityId : bigint(19) <<FK>>
  IssueTypeId : bigint(19) <<FK>>
  CuurentStatusId : bigint(19) <<FK>>
  CurrentResolvationId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.IssueComment" as issueComment {
  *Id : bigint(19) <<serial>>
  --
  *IssueId : bigint(19) <<FK>>
  *Comment : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.IssueAttachment" as issueAttachment {
  *Id : bigint(19) <<serial>>
  --
  *IssueId : bigint(19) <<FK>>
  *DocumentId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.Release" as release {
  *Id : bigint(19) <<serial>>
  --
  *ProjectId : bigint(19) <<FK>>
  *VersionNumber : varchar(20) <<unique>>
  ReleaseDate : date
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ReleaseIssue" as releaseIssue {
  *Id : bigint(19) <<serial>>
  --
  *ReleaseId : bigint(19) <<FK>>
  *IssueId : bigint(19) <<FK>>
  IsFinalized : boolean
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.WorkLog" as workLog {
  *Id : bigint(19) <<serial>>
  --
  *IssueId : bigint(19) <<FK>>
  *LogDate : date
  *StartWorkTime : time
  WorkingDuration : float 
  TimeUnitId : bigint(19) <<FK>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}


entity "ProjectManagement.WorkflowEligibleFileExtention" as workflowEligibleFileExtention {
  *Id : bigint(19) <<serial>>
  --
  *WorkflowId : bigint(19) <<FK>>
  *FileExtentionId : bigint(19) <<FK>>
  MaxFileSizeForUpload : integer
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}


entity "ProjectManagement.IssueWorkflowHistory" as issueWorkflowHistory {
  *Id : bigint(19) <<serial>>
  --
  *IssueId : bigint(19) <<FK>>
  *StartStatusId : bigint(19) <<FK>>
  *EndStatusId : bigint(19) <<FK>>
  *ProjectWorkflowProgressId : bigint(19) <<FK>>
  ResolvationId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.ProjectMeeting" as projectMeeting {
  *Id : bigint(19) <<serial>>
  --
  *ProjectId : bigint(19) <<FK>>
  *MeetingTypeId : bigint(19) <<FK>>
  *MeetingDate : date
  *Title : varchar(200)
  *Location : varchar(200)
  MinutesDocumentId : bigint(19) <<FK>>
  Description : varchar(4000)
  ScheduleStartTime : time
  ScheduleEndTime : time
  ActualStartTime : time
  ActualEndTime : time
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "ProjectManagement.MeetingInvitees" as meetingInvitees {
  *Id : bigint(19) <<serial>>
  --
  *ProjectMeetingId : bigint(19) <<FK>>
  *StaffId : bigint(19) <<FK>>
  *IsAttanded : boolean
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}


entity "ProjectManagement.MeetingMinutes" as meetingMinutes {
  *Id : bigint(19) <<serial>>
  --
  *ProjectMeetingId : bigint(19) <<FK>>
  *Resolution : varchar(4000)
  ResponsibleDepartmentId : bigint(19) <<FK>>
  IssueId : bigint(19) <<FK>>
  DueDate : datetime
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Finance.StaffContract" as staffContract {
  *Id : bigint(19) <<serial>>
  --
  *StaffId : bigint(19) <<FK>>
  *ContractTypeId : bigint(19) <<FK>>
  *StartDate : date
  *EndDate : date
  *Title : varchar(200)
  Description : varchar(4000)
  AutoRenewal : boolean
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Finance.ContractSallaryItem" as contractSallaryItem {
  *Id : bigint(19) <<serial>>
  --
  *ContractId : bigint(19) <<FK>>
  *Title : varchar(200)
  *Amount : numeric(22,2)
  Description : varchar(4000)
  *CalculationTimeUnitId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Finance.ContractDeductionItem" as contractDeductionItem {
  *Id : bigint(19) <<serial>>
  --
  *ContractId : bigint(19) <<FK>>
  *Title : varchar(200)
  *CalculationType : <<percentage=1, fixedAmount=2>>
  DeductionPercentage : numeric(3,2) <<from 0 until 100>>
  FixedAmount : numeric(22,2)
  Description : varchar(4000)
  *CalculationTimeUnitId : bigint(19) <<FK>>
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Finance.Supplier" as supplier {
  *Id : bigint(19) <<serial>>
  --
  *Title : bigint(19) <<FK>>
  Description : varchar(4000)
  Address : varchar(4000)
  PhoneNumber : varchar(20)
  MobileNumber : varchar(20)
  Email : varchar(100)
  PostalCode : varchar(20)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Finance.CostReceipt" as costReceipt {
  *Id : bigint(19) <<serial>>
  --
  *SupplierId : bigint(19) <<FK>>
  *DocumentId : bigint(19) <<FK>>
  *ReceiptDate : bigint(19) <<FK>>
  *TotalAmount : numeric(22,2)
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Finance.CostReceiptItem" as costReceiptItem {
  *Id : bigint(19) <<serial>>
  --
  *CostReceiptId : bigint(19) <<FK>>
  *ItemTitle : bigint(19) <<FK>>
  *UnitAmount : numeric(22,2)
  *Quantity : float
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Finance.ProjectDirectCostItem" as projectDirectCostItem {
  *Id : bigint(19) <<serial>>
  --
  *ProjectId : bigint(19) <<FK>>
  *CostReceiptItemId : bigint(19) <<FK>>
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Finance.CostPaymentReceipt" as costPaymentReceipt {
  *Id : bigint(19) <<serial>>
  --
  *CostReceiptId : bigint(19) <<FK>>
  *DocumentId : bigint(19) <<FK>>
  *Amount : numeric(22,2)
  *PaymentDate : date
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}

entity "Finance.SallaryPaymentReceipt" as sallaryPaymentReceipt {
  *Id : bigint(19) <<serial>>
  --
  *ContractId : bigint(19) <<FK>>
  *DocumentId : bigint(19) <<FK>>
  *Amount : numeric(22,2)
  *PaymentDate : date
  Description : varchar(4000)
  *IsActive : boolean <<default: true>>
  *IsDeleted : boolean <<default: false>>
  *CreateDate: timestamp <<default: now()>>
  *CreatorId : bigint(19)
  ModifyDate: timestamp
  ModifierId : bigint(19)
}


form ||..o{ formPermission
permission ||..o{ formPermission
role ||..o{ rolePermission
permission ||..o{ rolePermission
groups ||..o{ groupPermission
permission ||..o{ groupPermission
user ||..o{ userPermission
permission ||..o{ userPermission
user ||..o{ userRole
role ||..o{ userRole
user ||..o{ userGroup
groups ||..o{ userGroup
company |o..o{ company
company ||..o{ department
position |o..o{ position
department ||..o{ position
company ||..o{ staff
profile ||..o{ staff
position ||..o{ staffPosition
staff ||..o{ staffPosition
profile ||..o{ user
profile ||..o{ profileEducation
educationLevel ||..o{ profileEducation
profile ||..o{ profileCertificate
profile ||..o{ profileJobExperience
project ||..o{ issue
issueType ||..o{ issue
priority ||..o{ issue
staff ||..o{ issue
status ||..o{ issue
resolvation ||..o{ issue
project ||..o{ projectWorkflow
projectWorkflow ||..o{ projectWorkflowStatus
projectWorkflowStatus ||..o{ projectWorkflowProgress
projectWorkflowStatus ||..o{ projectWorkflowProgress
issue ||..o{ issueComment
project ||..o{ projectMeeting
staff ||..o{ meetingInvitees
projectMeeting ||..o{ meetingInvitees
department ||..o{ meetingMinutes
projectMeeting ||..o{ meetingMinutes
issue ||..o{ issueAttachment
document ||..o{ issueAttachment
document ||..o{ projectMeeting
meetingType ||..o{ projectMeeting
documentType ||..o{ document
fileExtention ||..o{ document
projectWorkflow ||..o{ workflowEligibleFileExtention
fileExtention ||..o{ workflowEligibleFileExtention
issue ||..o{ workLog
timeUnit ||..o{ workLog
issue ||..o{  issueWorkflowHistory
status ||..o{ issueWorkflowHistory
status ||..o{ issueWorkflowHistory
projectWorkflowProgress ||..o{ issueWorkflowHistory
resolvation ||..o{ issueWorkflowHistory
questionnaire ||..o{ questionnaireTargetDepartment
department ||..o{ questionnaireTargetDepartment
questionnaire ||..o{ question
question ||..o{ questionOption
questionnaire ||..o{ questionnaireResult
staff ||..o{ questionnaireResult
questionnaireResult ||..o{ questionnaireResultDetail
question ||..o{ questionnaireResultDetail
questionOption ||..o{ questionnaireResultDetail
project ||..o{ release
release ||..o{ releaseIssue
issue ||..o{ releaseIssue
project ||..o{ projectStaffMember
staff ||..o{ projectStaffMember
project ||..o{ projectDepartmentMember
department ||..o{ projectDepartmentMember
company ||..o{ workingTimeTable
company ||..o{ holidaies
staff ||..o{ attendance
staff ||..o{ leave
staff ||..o{ workMission
contractType ||..o{ staffContract
staff ||..o{ staffContract
staffContract ||..o{ contractSallaryItem
timeUnit ||..o{ contractSallaryItem
supplier ||..o{ costReceipt
document ||..o{ costReceipt
costReceipt ||..o{ costReceiptItem
costReceiptItem ||..o{ projectDirectCostItem
project ||..o{ projectDirectCostItem
costReceiptItem ||..o{ projectDirectCostItem
costReceipt ||..o{ costPaymentReceipt
document ||..o{ costPaymentReceipt
staffContract ||..o{ contractDeductionItem
timeUnit ||..o{ contractDeductionItem
document ||..o{ sallaryPaymentReceipt
contract ||..o{ sallaryPaymentReceipt
projectWorkflow ||..o{ projectWorkflowDocumentType
documentType ||..o{ projectWorkflowDocumentType
document ||..o{ profileEducation
@enduml