@startuml

skinparam Shadowing True
skinparam titleFontSize 24pt

skinparam interface{
  BackgroundColor #Black
}

skinparam component{
  BackgroundColor #Orange
}

skinparam file{
  BackgroundColor #lightsalmon
}

skinparam package{
  BackgroundColor #lightblue
}

skinparam node{
  BackgroundColor #Yellow
}

skinparam database{
  BackgroundColor #Lightgreen
}

title Horizon Research Project (HRP) \n Component Diagram \n Version 25.5.27




component "Chrome or Firefox" as browser <<web browser>>
component "Nginx" as webServer1 <<web server>>{
  portin "443" as ws1443
  artifact "Horizon App" as horizonApp
}
component "Nginx" as webServer <<web Server>>{
  portin "443" as ws443
  artifact "Horizon APIs" as horizonApis
  artifact "Administration Services" as adminServices
  artifact "HR Management Services" as hrServices
  artifact "Project Management Services" as proServices
  artifact "Finance Management Services" as hrServices
  artifact "Quality Management Services" as qcServices
  artifact "Productivity Assessment Services" as paServices
  artifact "Connector Services" as conServices
}

database "PostgreSQL" as rdbms <<rdbms>>{
  portin "5432" as pogresql5432
  artifact "Main Database" as mainDb
}

package "Third Party Apps" as thirdPartyApps{
  component "Jira" as jira <<Third Party Api>>
  component "Trello" as trello <<Third Party Api>>
  component "File Excel" as fileExcel <<File>>
  component "GitHub" as gitHub <<Third Party Api>>
  component "GitLab" as gitLab <<Third Party Api>>
  component "Bitbucket" as bitbucket <<Third Party Api>>
  component "Email" as email <<Third Party Api>>
  component "Calendar" as calendar <<Third Party App>>
}

component "Python 3.x" as python3<<sdk>>
component "flask" as flask <<web framework>>

component "SQLAlchamey" as sqlalchamey <<ORM framework>>
component "psycopg2" as psycopg2 <<data provider>>
() "User Access" as userAccess
() "HTTPS" as https1
() "HTTPS" as https2
() "HTTPS" as https3
() "TCP" as tcp

userAccess - browser
https1 -- ws1443
ws1443 --> horizonApp
browser --> https1
https2 -- ws443
horizonApp -->  https2
horizonApis .> flask : <<user>>
ws443 --> horizonApis 
horizonApis --> conServices
horizonApis --> adminServices
horizonApis --> hrServices
horizonApis --> proServices
horizonApis --> qcServices
horizonApis --> paServices

conServices --> https3

https3 --> trello
https3 --> jira
https3 --> fileExcel
https3 --> gitHub
https3 --> gitLab
https3 --> bitbucket
https3 --> email
https3 --> calendar

adminServices --> sqlalchamey
hrServices --> sqlalchamey
proServices --> sqlalchamey
qcServices --> sqlalchamey
paServices --> sqlalchamey
conServices --> sqlalchamey

flask .> python3 : <<use>>
sqlalchamey .> python3 : <<use>>
psycopg2 .> python3 : <<use>>


sqlalchamey --> psycopg2

psycopg2 --> tcp

tcp -- pogresql5432
pogresql5432 --> mainDb
@enduml