@startuml
left to right direction

:Technical Staff: as TechnicalStaff
:Technical Manager: as TechnicalManager
:Senior Manager: as SeniorManager
:Project Manager: as PMO
:Financial Manager: as Fmanager
:Administrator: as Admin
:Human Resource: as HR
:Accountant: as Accountant

package "Auth"{
    usecase "Role Management" as roleManagement
    usecase "Role Registration" as roleRegistration
    usecase "Role Update" as roleUpdate
    usecase "Role Activation" as roleActivation
    usecase "User Management" as userManagement
    usecase "User Registration" as userRegistration
    usecase "User Activation" as userActivation
    usecase "Update Profile" as updateProfile
    usecase "View Profile" as viewProfile
    usecase "Change Password" as changePassword
    usecase "Authenitication" as authentication
    usecase "Login" as login
    usecase "Create Token" as createToken
    usecase "Authorization" as authorization
    usecase "Grant Role" as grantRole
    usecase "User Restriction" as userRestriction
    usecase "Check User Role Grant" as checkGrant

}

userManagement .> roleManagement

roleManagement ..> roleRegistration : <<include>>
roleManagement ..> roleUpdate : <<include>>
roleManagement ..> roleActivation : <<include>>
userManagement ..> userRegistration :<<include>>
userManagement ..> userActivation :<<include>>
userManagement ..> updateProfile :<<include>>
userManagement ..> viewProfile :<<include>>
userManagement ..> changePassword :<<include>>

authentication ..> userRegistration
authentication ..> login : <<include>>
authentication ..> createToken : <<include>>

authorization ..>  roleManagement
authorization ..> authentication 
authorization ..> userManagement

grantRole <.. authorization : <<include>>
userRestriction <.. authorization : <<include>>
checkGrant <.. authorization : <<include>>

@enduml