@startuml
left to right direction

skinparam useCaseBackgroundColor #Business
skinparam actorBackgroundColor #Business
skinparam Shadowing True

title Horizon Research Project: Overall Use Case Diagram

:User: as User
:Senior Manager: as SeniorManager
:Project Manager: as PMO
:Network Manager: as NetworkManager
:Financial Manager: as Fmanager
:Administrator: as Admin
:Human Resource: as HR
:Accountant: as Accountant
:Staff: as Staff
:DevOps Manager: as DevOpsManager
:Logestics Manager: as LogesticsManager
:Product Manager: as ProductManager


package "Auth"{
    usecase "Role Management" as roleManagement
    usecase "User Management" as userManagement
    usecase "Profile Management" as profileManagement
    usecase "Authenitication" as authentication
    usecase "Authorization" as authorization
}

package "Organization"{
    usecase "Organization Management" as organizationManagement
    usecase "Building Management" as buildingManagement
    usecase "Work Stattion Management" as workStationManagement
    usecase "Department Management" as departmentManagement
}

package "HR Management"{
    usecase "Position Management" as positionManagement
    usecase "Staff Management" as staffManagement
    usecase "Attendance Management" as attendanceManagement
}

package "Resources"{
    usecase "Asset Management" as assetManagement
}

package "Project"{
    usecase "Project Management" as projectManagement
    usecase "Project Team Management" as projectTeamManagement
    usecase "Release Management" as releaseManagement
    usecase "Issue Management" as issueManagement
    usecase "Meeting Management" as meetingManagement
    usecase "Timesheet Management" as timesheetManagement
}

package "Reporting"{
    usecase "Business Intelligence (BI) Reports" as biReport
    usecase "Projects Reports" as projectReport
    usecase "Financial Reports" as financialReport
    usecase "Log Reports" as logReport
}


package "Financial"{
    usecase "Project Costing" as costing
    usecase "Bugget Management" as bugget
    usecase "Product Pricing" as pricing
    usecase "Salary Management" as salaryManagement
}



User --> authentication
User --> authorization
User --> profileManagement
Staff --> attendanceManagement
roleManagement <-- Admin
userManagement <-- Admin
staffManagement <-- HR
staffManagement <-- Staff
Accountant --> salaryManagement
Accountant --> costing
Accountant --> pricing
Accountant --> bugget
pricing <-- ProductManager
costing <-- PMO
SeniorManager --> bugget
positionManagement <-- HR
departmentManagement <-- HR
organizationManagement <-- HR
buildingManagement <-- HR
PMO --> projectManagement
PMO --> projectTeamManagement
PMO --> releaseManagement
PMO --> meetingManagement
ProductManager --> releaseManagement
ProductManager --> projectManagement
HR --> calendarManagement
assetManagement <-- PMO
calendarManagement <-- PMO
LogesticsManager --> assetManagement
Fmanager --> assetManagement

releaseManagement <-- DevOpsManager
issueManagement <-- Staff
meetingManagement <-- Staff
timesheetManagement <-- Staff

Admin --> logReport
Fmanager --> financialReport
SeniorManager --> financialReport
SeniorManager --> biReport
projectReport <-- PMO
salaryManagement <-- Fmanager
NetworkManager --> workStationManagement

@enduml