@startuml
left to right direction

skinparam useCaseBackgroundColor #Business

title Overall Use Case Diagram

note "This diagram shows relationships \n between usecases and domains in a snapshot." as a

:User: as User
:Technical Staff: as TechnicalStaff
:Technical Manager: as TechnicalManager
:Senior Manager: as SeniorManager
:Project Manager: as PMO
:Financial Manager: as Fmanager
:Administrator: as Admin
:Human Resource: as HR
:Accountant: as Accountant

package "Auth"{
    usecase "Role Management" as roleManagement
    usecase "User Management" as userManagement
    usecase "Profile Management" as profileManagement
    usecase "Authenitication" as authentication
    usecase "Authorization" as authorization
}

package "Organization"{
    usecase "Organization Management" as organizationManagement
    usecase "Department Management" as departmentManagement
}

package "Staff"{
    usecase "Position Management" as positionManagement
    usecase "Staff Management" as staffManagement
}

package "Project"{
    usecase "Project Management" as projectManagement
    usecase "Project Team Management" as projectTeamManagement
}

userManagement .> roleManagement
authorization ..>  roleManagement
authorization ..> authentication 
authorization ..> userManagement
profileManagement ..> userManagement
profileManagement ..> authentication

User -- authentication
User -- authorization
User -- profileManagement
roleManagement -- Admin
userManagement -- Admin
staffManagement -- HR
positionManagement -- HR
departmentManagement -- HR
organizationManagement -- HR
PMO -- projectManagement
PMO -- projectTeamManagement

staffManagement ..> userManagement
staffManagement .> positionManagement
staffManagement ..> departmentManagement
positionManagement ..> departmentManagement
departmentManagement .> organizationManagement
projectManagement ..> organizationManagement
projectTeamManagement .> projectManagement
projectTeamManagement ..> positionManagement
projectTeamManagement ..> staffManagement

@enduml