@startuml

skinparam actorBackgroundColor #Business

title Hierarchy of Actors

:User: as User
:Staff: as Staff
:Manager: as Manager
:Technical Staff: as TechnicalStaff
:Manager: as Manager
:Senior Manager: as SeniorManager
:Project Manager: as PMO
:Financial Manager: as Fmanager
:Administrator: as Admin
:Human Resource: as HR
:Accountant: as Accountant
:DevOps Manager: as DevOpsManager
:Developer: as Developer
:Tester: as Tester
:Analyzer: as Analyzer

User <|--- Admin
User <|-- Staff

Staff <|-- TechnicalStaff
Staff <|-- Accountant
Staff <|---- Manager

TechnicalStaff <|-- Developer
TechnicalStaff <|-- Tester
TechnicalStaff <|-- Analyzer

Manager <|-- SeniorManager
Manager <|-- PMO
Manager <|-- Fmanager
Manager <|-- DevOpsManager
Manager <|-- HR

@enduml