@startuml

skinparam actorBackgroundColor #Business

title Horizon Research Project: Hierarchy of Actors

:User: as User
:Staff: as Staff
:Manager: as Manager
:Technical Staff: as TechnicalStaff
:Manager: as Manager
:Senior Manager: as SeniorManager
:Project Manager: as PMO
:Financial Manager: as Fmanager
:Administrator: as Admin
:Human Resource: as HR
:Accountant: as Accountant
:DevOps Manager: as DevOpsManager
:Developer: as Developer
:Tester: as Tester
:Analyzer: as Analyzer
:Logestics Manager: as LogesticsManager
:Product Manager: as ProductManager
:Support: as Support
:Security: as Security
:Database Admin: as DbAdmin

User <|--- Admin
User <|-- Staff

Staff <|-- TechnicalStaff
Staff <|-- Accountant
Staff <|---- Manager

TechnicalStaff <|-- Developer
TechnicalStaff <|-- Tester
TechnicalStaff <|-- Analyzer
TechnicalStaff <|-- Support
TechnicalStaff <|-- Security
TechnicalStaff <|-- DbAdmin

Manager <|-- SeniorManager
Manager <|-- PMO
Manager <|-- Fmanager
Manager <|-- DevOpsManager
Manager <|-- HR
Manager <|-- LogesticsManager
Manager <|-- ProductManager

@enduml